[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=1F58E0D1C5426A8F290794B9451FB0A9
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/pcs-host-actor
GameDefaultMap=/Game/pcs-host-actor

[/Script/Engine.Engine]
; Allow close inspection of point clouds (centimeters; engine default is 10).
NearClipPlane=0.100000

